[build]
  # 1. Install dependencies from requirements.txt
  # 2. Run 'flet publish' to build the static site (default entry is main.py)
  command = "echo 'Done'"

  # The directory where flet puts the built files
  publish = "build/web"

